version: '{build}'
skip_tags: true
clone_depth: 10

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true  # Enables fast failing.


os: Windows Server 2012
init:
  - git config --global core.autocrlf true
build_script:
  - mvn clean package -B -Dmaven.test.skip=true
test_script:
  - mvn clean install --batch-mode -Pqulice
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
